### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by shinyaogata** [sammy-suyama/PythonBayesianMLBook#1]
PythonBayesianMLBookリポジトリ内のソースコード類はどういったライセンス形態で公開されているのでしょうか？

**Comment by sammy-suyama** [comment]
ご連絡ありがとうございます。ライセンスを付与したのでご確認ください。

**Comment by shinyaogata** [comment]
@sammy-suyama ご対応ありがとうございました。いつも sammy-suyama さんの書籍で勉強させていただいてます。
