### ISSUE TITLE
極めて軽微な誤植

### ISSUE THREAD

**Issue by YasuyukiSaito2654** [sammy-suyama/PythonBayesianMLBook#2]
極めて細かい話で恐縮ですが，1_3_代表的な確率分布.ipynb での
二項分布（binomial distribution）入力[14]  # サンプル化から分散を計算
ポアソン分布（Poisson distribution）入力[18]   # サンプル化から分散を計算
は，いずれも「化」は削除して「サンプルから分散を計算」かと存じます．
書籍では，そのようになっております．

また，一様分布（uniform distribution）の入力[23] および出力[23] は不要ではないでしょうか（入力[21] および出力[21] で既出のため）．

**Comment by Gashin-Learning** [comment]
ご指摘ありがとうございます。修正しました。
