### ISSUE TITLE
p47のコードのタイポについて

### ISSUE THREAD

**Issue by KazuOKB** [sammy-suyama/PythonBayesianMLBook#3]
私が間違っているかもしれないのですが、p47の最初のコードにある自己相関のプロットについて、axes[0]はposterior_large_stepをプロットしている一方でタイトルにはstep size=0.01（一番ステップ幅が小さいもの）になっていました。これはaxes[1]でプロットしているposterior_small_stepと逆になっているのではないかと思ったのですが、正しいでしょうか？

仮に正しいとして図1.10を見直すと、真ん中の図(step size=0.01)は収束に向かっているが、ステップ幅が小さすぎてサンプル数が足りていない様子を表していると解釈できたりしますか？

他方で、図1.10の上の図(step size=10.0)は、自己相関が一旦なくなるもののステップ幅が大きすぎるために再び自己相関を持ってしまうと解釈できたりしますか？

よろしくお願いします。

**Comment by kidaufo** [comment]
ご指摘ありがとうございます。
おっしゃる通り、p47でプロットするデータとタイトルの対応が間違っておりました。図1.10の一番上がstep size=10.0, 真ん中がstep size=0.01となります。

> 仮に正しいとして図1.10を見直すと、真ん中の図(step size=0.01)は収束に向かっているが、ステップ幅が小さすぎてサンプル数が足りていない様子を表していると解釈できたりしますか？
> 
> 他方で、図1.10の上の図(step size=10.0)は、自己相関が一旦なくなるもののステップ幅が大きすぎるために再び自己相関を持ってしまうと解釈できたりしますか？

書籍での説明に補足させていただくと、ラグが増えるにつれて自己相関が速やかに0に近づく場合（図1.10の一番下の図）に、MCMCで効率の良いサンプリングができていると考えます。
ステップ数が小さい場合でもラグを十分大きくすれば自己相関が0に近づいては行きますが、いずれにせよそのステップ数ではサンプリングの効率が悪いという判断になります。

**Comment by KazuOKB** [comment]
返信いただきありがとうございます。
自分の勘違いでなくてよかったです。また、自己相関が収束しない場合（図1.10の上2つ）の解釈も問題なさそうでよかったです。
補足まで頂きありがとうございます。
