### ISSUE TITLE
メトロポリス・ヘイスティングス法の実装について

### ISSUE THREAD

**Issue by mm0824kb** [sammy-suyama/PythonBayesianMLBook#4]
p43の下段のプログラムの4, 5行目ですが、「攪乱項εは平均0の一様分布に従うとする」とあり、一様分布からサンプリングしています。
しかしながら、p42には提案分布を正規分布とするとありますので、この通り実装するのであれば、正規分布からサンプリングしないといけないのではないでしょうか？
間違えていたら申し訳ございませんが、ご確認宜しくお願い致します。

**Comment by kidaufo** [comment]
ご指摘ありがとうございます。
ご認識の通り、本文での説明とコードの内容が一貫しておらず、著者のミスになります。混乱を招いてしまい大変申し訳ございません。

p43の下段のプログラム5行目は正しくは、

`x_proposal = x_current + step_size * np.random.randn()`
もしくは
`x_proposal = x_current + np.random.normal(0, step_size)`

とすべきでした。修正前後で以降の結果には大きな影響はありませんが、実装と図は今後修正するようにいたします（p45も同様に修正します）。

また、p39の説明も紛らわしく申し訳ありませんが、εが一様分布（やその他の対称な確率分布）に従う場合も含めて、ランダムウォークMH法と呼ぶ認識です。ただしTFP, PyMCなどはどちらもデフォルトでは正規分布を採用しているようなので、そうするのが一般的と思われます。

参考
- TFPのドキュメント：https://www.tensorflow.org/probability/api_docs/python/tfp/mcmc/RandomWalkMetropolis
- 上記ドキュメントで参照している論文のsection 2.1：https://projecteuclid.org/journals/probability-surveys/volume-1/issue-none/General-state-space-Markov-chains-and-MCMC-algorithms/10.1214/154957804100000024.full

**Comment by mm0824kb** [comment]
ご確認いただき有難うございます。
おっしゃる通り、本件は提案分布の仮定と実装が合っていなかっただけで、収束している以上、結果に大きな影響はないというのはその通りかと思いました。
提案分布を一様分布と仮定していればコード上も問題がなかったと思いますので、一様にするかx_t-1の周りで重みづけをするかぐらいの差かなと考えます。
念のためですが、p45のコードも同様かと思います。

p39のご説明については、個人的にはすっと入ってきましたので大丈夫です！
何となく一様分布にするよりは正規分布にする方が、x_t-1で重みづけをしてサンプリングするので効率が良さそうですし、あまり複雑な分布にしても効果は大きくなさそうなので、正規分布が一番良いのでしょうかね。

ご回答いただき、誠にありがとうございました。
引き続きこの本で勉強していこうと思いますので、宜しくお願い致します。
